apiVersion: v1
kind: Secret
metadata:
  name: backend-password
  namespace: developer
type: Opaque
data:
  POSTGRES_PASSWORD: UE9TVEdSRVNfUEFTU1dPUkQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-password
  namespace: admin
type: Opaque
data:
  POSTGRES_PASSWORD: UE9TVEdSRVNfUEFTU1dPUkQ=