apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - image: randybrown12/php-app:v1.0.0
          name: php-app
          ports:
          - containerPort: 80
          envFrom:
            - configMapRef: 
                name: pod-v1.0.0