apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: randybrown12/php-app:v1.0.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 800m
        envFrom:
          - configMapRef: 
              name: pod-v1.0.0
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: php-app-autoscaler
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-deployment
  updatePolicy:
    updateMode: Auto
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
    - containerName: php-app
      minAllowed:
        cpu: 200m
      maxAllowed:
        cpu: 500m
      controlledResources: ["cpu"]