apiVersion: batch/v1
kind: Job
metadata:
  name: hey-program-job
spec:
  template:
    spec:
      containers:
      - name: hey-program
        image: williamyeh/hey
        args: ["-n", "1000000", "-c", "5", "http://php-service.default.svc.cluster.local:80"]
        ports:
        - containerPort: 80
      restartPolicy: Never
  backoffLimit: 2