FROM python:3.10-slim

WORKDIR /app

COPY flaskweb.py .

COPY templates /app/templates

RUN apt-get update && pip install flask psycopg2-binary prometheus-flask-exporter

EXPOSE 5000

CMD ["flask", "--app", "flaskweb", "run", "--host=0.0.0.0", "--port=5000"]