apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service-to-flaskapp2
spec:
  selector:
    app: flaskapp-2
  ports:
    - port: 81
      targetPort: 5000
  clusterIP: 10.96.0.26
  type: ClusterIP