apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-for-flaskapp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: persistent-volume-claim-for-flaskapp
  persistentVolumeReclaimPolicy: Delete
  hostPath: 
    path: /run/desktop/mnt/host/c/Users/Randy/Desktop/Coding_Semester/Independent_Study/W3-4Notes/data/
    type: Directory
  storageClassName: manual
  