apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-for-flaskapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual