apiVersion: v1
kind: Namespace
metadata:
  name: developer
  labels:
    name: developer
---
apiVersion: v1
kind: Namespace
metadata:
  name: admin
  labels:
    name: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-account
  namespace: developer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-account
  namespace: admin