apiVersion: v1
kind: Pod
metadata:
  name: flaskapp-frontend
  namespace: developer
  labels: 
    app: flaskapp-frontend
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "webapp"
    vault.hashicorp.com/agent-inject-secret: 'secret/flaskapp-backend-w15-16'
    vault.hashicorp.com/agent-inject-template-config.json: |
      {{- with secret "secret/flaskapp-backend-w15-16" -}}
      {{- .Data.data | toJSON -}}
      {{- end -}}
spec:
  serviceAccountName: dev-account
  containers:
  - name: flaskapp-frontend
    image: docker.io/randybrown12/flaskapp-frontend-w15-16:latest
    ports:
    - containerPort: 5000
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
---
apiVersion: v1
kind: Pod
metadata:
  name: flaskapp-frontend-admin
  namespace: admin
  labels: 
    app: flaskapp-frontend-admin
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "webapp"
    vault.hashicorp.com/agent-inject-secret: 'secret/flaskapp-backend-w15-16'
    vault.hashicorp.com/agent-inject-template-config.json: |
      {{- with secret "secret/flaskapp-backend-w15-16" -}}
      {{- .Data.data | toJSON -}}
      {{- end -}}
spec:
  serviceAccountName: admin-account
  containers:
  - name: flaskapp-frontend-admin
    image: docker.io/randybrown12/flaskapp-frontend-w15-16:latest
    ports:
    - containerPort: 5000
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
---
apiVersion: v1
kind: Pod
metadata:
  name: flaskapp-backend
  namespace: developer
  labels: 
    app: flaskapp-backend
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "webapp"
    vault.hashicorp.com/agent-inject-secret-config: 'secret/flaskapp-backend-w15-16'
    vault.hashicorp.com/agent-inject-template-config: |
      {{- with secret "secret/flaskapp-backend-w15-16" -}}
      export POSTGRES_USER={{ .Data.data.POSTGRES_USER }}
      export POSTGRES_PASSWORD={{ .Data.data.POSTGRES_PASSWORD }}
      export POSTGRES_DB={{ .Data.data.POSTGRES_DB }}
      {{- end }}
spec:
  serviceAccountName: dev-account
  containers:
  - name: flaskapp-backend
    image: docker.io/randybrown12/flaskapp-backend-w15-16:latest
    ports:
    - containerPort: 5432
    command: ["/bin/sh", "-c"]
    args:
      - |
        . /vault/secrets/config && exec docker-entrypoint.sh postgres