apiVersion: v1
kind: Pod
metadata:
  name: flaskapp-frontend
  labels: 
    app: flaskapp-frontend
spec:
  containers:
  - name: flaskapp-frontend
    image: docker.io/randybrown12/flaskapp-frontend-w5-6:latest
    envFrom:
    - configMapRef:
        name: postgres-info
    - secretRef:
        name: backend-password
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: flaskapp-backend
  labels: 
    app: flaskapp-backend
spec:
  containers:
  - name: flaskapp-backend
    image: docker.io/randybrown12/flaskapp-backend-w5-6:latest
    envFrom:
    - configMapRef:
        name: postgres-info
    - secretRef:
        name: backend-password
    ports:
    - containerPort: 5432